name: Latest blog posts

on:
  schedule:
    - cron: "17 16 * * *"
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - ".github/workflows/blog-posts.yml"

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://blog.100067.xyz/rss.xml"
          max_post_count: 6
          committer_username: liuqitoday
          committer_email: liuqitoday@163.com
